### ISSUE TITLE
v1.0.2 - Errors with MudBlazor 7.1 on CodeBlock

### ISSUE THREAD

**Issue by erik-aie** [MyNihongo/MudBlazor.Markdown#269]
Hey y'all! 

I'm trying to use this package with MudBlazor 7.1, which I'm not sure if is entirely supported by this package at this point, but I'm running into errors when I use a Code Block component and lists. Standard Bold, Italics, Bold Italics work, but Code Block throws 2 exceptions on render and lists don't render bullets. If y'all have a build that works for 7.x, I'd really appreciate that build being released even as pre-release so I can keep moving with this project.

Here's the behavior I'm seeing
![CleanShot 2024-07-11 at 10 25 32](https://github.com/MyNihongo/MudBlazor.Markdown/assets/106224128/4ff3a3b5-2645-4555-9fe7-efaf344553d2)

And the basic Code:
```
    <MudItem xs="12" Class="pb-0">
        <MudTextField T="string"
                      @bind-Value="_content"
                      AutoGrow="true"
                      Disabled="_isLoading"
                      Lines="2"
                      Variant="Variant.Outlined"
                      Placeholder="Content"
                      Immediate="true"
                      HelperText="@ContentHelperText"
                      MaxLength="_contentCharLimit"/>
    </MudItem>
    <MudItem xs="12" Class="pt-2">
        <MudText Typo="Typo.subtitle2">Preview</MudText>
        <MudMarkdown Value="@_content"/>
    </MudItem>
```

Here are the exceptions thrown by Code Block:
```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not find 'setHighlightStylesheet' ('setHighlightStylesheet' was undefined).
      Error: Could not find 'setHighlightStylesheet' ('setHighlightStylesheet' was undefined).
          at https://localhost:7119/_framework/blazor.webassembly.js:1:368
          at Array.forEach (<anonymous>)
          at l.findFunction (https://localhost:7119/_framework/blazor.webassembly.js:1:336)
          at w (https://localhost:7119/_framework/blazor.webassembly.js:1:5079)
          at https://localhost:7119/_framework/blazor.webassembly.js:1:2872
          at new Promise (<anonymous>)
          at b.beginInvokeJSFromDotNet (https://localhost:7119/_framework/blazor.webassembly.js:1:2835)
          at Object.vn [as invokeJSJson] (https://localhost:7119/_framework/blazor.webassembly.js:1:58849)
          at https://localhost:7119/_framework/dotnet.runtime.8.0.5.gd6neq3kwe.js:3:178364
          at Tl (https://localhost:7119/_framework/dotnet.runtime.8.0.5.gd6neq3kwe.js:3:179198)
Microsoft.JSInterop.JSException: Could not find 'setHighlightStylesheet' ('setHighlightStylesheet' was undefined).
Error: Could not find 'setHighlightStylesheet' ('setHighlightStylesheet' was undefined).
    at https://localhost:7119/_framework/blazor.webassembly.js:1:368
    at Array.forEach (<anonymous>)
    at l.findFunction (https://localhost:7119/_framework/blazor.webassembly.js:1:336)
    at w (https://localhost:7119/_framework/blazor.webassembly.js:1:5079)
    at https://localhost:7119/_framework/blazor.webassembly.js:1:2872
    at new Promise (<anonymous>)
    at b.beginInvokeJSFromDotNet (https://localhost:7119/_framework/blazor.webassembly.js:1:2835)
    at Object.vn [as invokeJSJson] (https://localhost:7119/_framework/blazor.webassembly.js:1:58849)
    at https://localhost:7119/_framework/dotnet.runtime.8.0.5.gd6neq3kwe.js:3:178364
    at Tl (https://localhost:7119/_framework/dotnet.runtime.8.0.5.gd6neq3kwe.js:3:179198)
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.Infrastructure.IJSVoidResult, Microsoft.JSInterop, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at MudBlazor.MudCodeHighlight.SetThemeAsync()
   at MudBlazor.MudCodeHighlight.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```
```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not find 'highlightCodeElement' ('highlightCodeElement' was undefined).
      Error: Could not find 'highlightCodeElement' ('highlightCodeElement' was undefined).
          at https://localhost:7119/_framework/blazor.webassembly.js:1:368
          at Array.forEach (<anonymous>)
          at l.findFunction (https://localhost:7119/_framework/blazor.webassembly.js:1:336)
          at w (https://localhost:7119/_framework/blazor.webassembly.js:1:5079)
          at https://localhost:7119/_framework/blazor.webassembly.js:1:2872
          at new Promise (<anonymous>)
          at b.beginInvokeJSFromDotNet (https://localhost:7119/_framework/blazor.webassembly.js:1:2835)
          at Object.vn [as invokeJSJson] (https://localhost:7119/_framework/blazor.webassembly.js:1:58849)
          at https://localhost:7119/_framework/dotnet.runtime.8.0.5.gd6neq3kwe.js:3:178364
          at Tl (https://localhost:7119/_framework/dotnet.runtime.8.0.5.gd6neq3kwe.js:3:179198)
Microsoft.JSInterop.JSException: Could not find 'highlightCodeElement' ('highlightCodeElement' was undefined).
Error: Could not find 'highlightCodeElement' ('highlightCodeElement' was undefined).
    at https://localhost:7119/_framework/blazor.webassembly.js:1:368
    at Array.forEach (<anonymous>)
    at l.findFunction (https://localhost:7119/_framework/blazor.webassembly.js:1:336)
    at w (https://localhost:7119/_framework/blazor.webassembly.js:1:5079)
    at https://localhost:7119/_framework/blazor.webassembly.js:1:2872
    at new Promise (<anonymous>)
    at b.beginInvokeJSFromDotNet (https://localhost:7119/_framework/blazor.webassembly.js:1:2835)
    at Object.vn [as invokeJSJson] (https://localhost:7119/_framework/blazor.webassembly.js:1:58849)
    at https://localhost:7119/_framework/dotnet.runtime.8.0.5.gd6neq3kwe.js:3:178364
    at Tl (https://localhost:7119/_framework/dotnet.runtime.8.0.5.gd6neq3kwe.js:3:179198)
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.Infrastructure.IJSVoidResult, Microsoft.JSInterop, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at MudBlazor.MudCodeHighlight.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

**Comment by erik-aie** [comment]
![CleanShot 2024-07-11 at 10 35 35](https://github.com/MyNihongo/MudBlazor.Markdown/assets/106224128/98e4502a-1734-4d2d-b7ff-b85caefe7958)

I removed the forced code color value in my app's CSS and it seems to have corrected this issue. Or maybe something else with hard refresh was broken, weird....but I think it's okay.

**Comment by Stone-Red-Code** [comment]
Same error in the samples project.
To me it seems like a bug that should actually be fixed.

**MudBlazor.Markdown.Server**

![image](https://github.com/user-attachments/assets/e6ef0685-c7c5-4fda-b856-d29506e16eac)

```
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'YkLWbWcdhqEK-K3N13k4uo7boJU1lRAVJfaosDag8XI'.
      Microsoft.JSInterop.JSException: Could not find 'highlightCodeElement' ('highlightCodeElement' was undefined).
Error: Could not find 'highlightCodeElement' ('highlightCodeElement' was undefined).
    at http://localhost:5000/_framework/blazor.server.js:1:537
    at Array.forEach (<anonymous>)
    at l.findFunction (http://localhost:5000/_framework/blazor.server.js:1:505)
    at _ (http://localhost:5000/_framework/blazor.server.js:1:5248)
    at http://localhost:5000/_framework/blazor.server.js:1:3041
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (http://localhost:5000/_framework/blazor.server.js:1:3004)
    at Xt._invokeClientMethod (http://localhost:5000/_framework/blazor.server.js:1:60890)
    at Xt._processIncomingData (http://localhost:5000/_framework/blazor.server.js:1:58279)
    at Xt.connection.onreceive (http://localhost:5000/_framework/blazor.server.js:1:51920)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at MudBlazor.MudCodeHighlight.OnAfterRenderAsync(Boolean firstRender) in C:\Users\David\Downloads\MudBlazor.Markdown-main\MudBlazor.Markdown-main\src\MudBlazor.Markdown\Components\MudCodeHighlight.razor.cs:line 129
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

**MudBlazor.Markdown.Wasm**

```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not find 'highlightCodeElement' ('highlightCodeElement' was undefined).
      Error: Could not find 'highlightCodeElement' ('highlightCodeElement' was undefined).
          at http://localhost:3996/_framework/blazor.webassembly.js:1:368
          at Array.forEach (<anonymous>)
          at l.findFunction (http://localhost:3996/_framework/blazor.webassembly.js:1:336)
          at w (http://localhost:3996/_framework/blazor.webassembly.js:1:5079)
          at http://localhost:3996/_framework/blazor.webassembly.js:1:2872
          at new Promise (<anonymous>)
          at b.beginInvokeJSFromDotNet (http://localhost:3996/_framework/blazor.webassembly.js:1:2835)
          at Object.vn [as invokeJSJson] (http://localhost:3996/_framework/blazor.webassembly.js:1:58849)
          at http://localhost:3996/_framework/dotnet.runtime.8.0.8.80cvijctdx.js:3:178428
          at Ll (http://localhost:3996/_framework/dotnet.runtime.8.0.8.80cvijctdx.js:3:179262)
Microsoft.JSInterop.JSException: Could not find 'highlightCodeElement' ('highlightCodeElement' was undefined).
Error: Could not find 'highlightCodeElement' ('highlightCodeElement' was undefined).
    at http://localhost:3996/_framework/blazor.webassembly.js:1:368
    at Array.forEach (<anonymous>)
    at l.findFunction (http://localhost:3996/_framework/blazor.webassembly.js:1:336)
    at w (http://localhost:3996/_framework/blazor.webassembly.js:1:5079)
    at http://localhost:3996/_framework/blazor.webassembly.js:1:2872
    at new Promise (<anonymous>)
    at b.beginInvokeJSFromDotNet (http://localhost:3996/_framework/blazor.webassembly.js:1:2835)
    at Object.vn [as invokeJSJson] (http://localhost:3996/_framework/blazor.webassembly.js:1:58849)
    at http://localhost:3996/_framework/dotnet.runtime.8.0.8.80cvijctdx.js:3:178428
    at Ll (http://localhost:3996/_framework/dotnet.runtime.8.0.8.80cvijctdx.js:3:179262)
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.Infrastructure.IJSVoidResult, Microsoft.JSInterop, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at MudBlazor.MudCodeHighlight.OnAfterRenderAsync(Boolean firstRender) in C:\Users\David\Downloads\MudBlazor.Markdown-main\MudBlazor.Markdown-main\src\MudBlazor.Markdown\Components\MudCodeHighlight.razor.cs:line 129
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```
