### ISSUE TITLE
LinkCommand causes error in MudBlazor v7.0.0

### ISSUE THREAD

**Issue by Stone-Red-Code** [MyNihongo/MudBlazor.Markdown#270]
Just loading a page which contains a `MudMarkdown ` with a `LinkCommand` property causes an error.

```razor
<MudMarkdown Value="@context.Content.TruncateLines(5)" OverrideHeaderTypo="(_)=>Typo.h6" LinkCommand="new BlogUtils.RedirectCommand(NavigationManager, context)" />
```

```
Unhandled exception in circuit 'N3QyxM0C5CCjeRO_d6vsvi1X2MxWspB_xBAXZOuXM3k'.
System.TypeLoadException: Could not load type 'MudBlazor.ColorMudEnumExtensions' from assembly 'MudBlazor, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at MudBlazor.MudLinkButton.get_Classname()
   at MudBlazor.MudLinkButton.BuildRenderTree(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
```

**Comment by MihailsKuzmins** [comment]
There is already a PR to support the latest MudBlazor, so it has probably been fixed there - https://github.com/MyNihongo/MudBlazor.Markdown/pull/266

Sorry for taking so long, we will try to merge it and release a new version during the next week.

**Comment by MihailsKuzmins** [comment]
I have installed [MudBlazor.Markdown v7.8.0](https://www.nuget.org/packages/MudBlazor.Markdown/) and there is no error.

![thomas-dm](https://github.com/user-attachments/assets/32cb8562-b3c9-48e4-a27b-9dda574242ee)

Code:
```razor
@page "/"
@using System.Reactive
@using ReactiveUI

<PageTitle>Index</PageTitle>

<MudText Typo="Typo.h3">My markdown</MudText>
<MudMarkdown Value="@Value" LinkCommand="ReactiveCommand.Create<string>(OnLinkClicked)" />

@code
{
    private string Value { get; } = "text *italics* and bold and this is a [link](https://www.mynihongo.org)";

    private void OnLinkClicked(string url)
    {
        Console.Write($"aaaa: {url}");
    }
}
```
