### ISSUE TITLE
Wasm sample project is not working

### ISSUE THREAD

**Issue by BeepBeepBopBop** [MyNihongo/MudBlazor.Markdown#279]
Hi, I would like to try your library and figured I would start by running the WASM sample but unfortunately it does not work out of the box on .NET8.

I get systematically get the following error:

Microsoft.JSInterop.JSException: Could not find 'highlightCodeElement' ('highlightCodeElement' was undefined).
Error: Could not find 'highlightCodeElement' ('highlightCodeElement' was undefined).
    at http://localhost:3996/_framework/blazor.webassembly.js:1:368
    at Array.forEach (<anonymous>)
    at l.findFunction (http://localhost:3996/_framework/blazor.webassembly.js:1:336)
    at w (http://localhost:3996/_framework/blazor.webassembly.js:1:5079)
    at http://localhost:3996/_framework/blazor.webassembly.js:1:2872
    at new Promise (<anonymous>)
    at b.beginInvokeJSFromDotNet (http://localhost:3996/_framework/blazor.webassembly.js:1:2835)
    at Object.vn [as invokeJSJson] (http://localhost:3996/_framework/blazor.webassembly.js:1:58849)
    at http://localhost:3996/_framework/dotnet.runtime.js:3:178428
    at Ll (http://localhost:3996/_framework/dotnet.runtime.js:3:179262)
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.Infrastructure.IJSVoidResult, Microsoft.JSInterop, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at MudBlazor.MudCodeHighlight.OnAfterRenderAsync(Boolean firstRender) in C:\Users\evanc\Downloads\MudBlazor.Markdown-main\src\MudBlazor.Markdown\Components\MudCodeHighlight.razor.cs:line 129
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

Thanks for your help

**Comment by MihailsKuzmins** [comment]
Have you followed the steps described in the [README file](https://github.com/MyNihongo/MudBlazor.Markdown/tree/main/samples/README.md) for the sample project?

# Debug
The following steps are required in order to run the samples:
- Download node.js from [downloads](https://nodejs.org/en/download/package-manager)
- Navigate to src\MudBlazor.Markdown
- Open a console and run `npm ci`
- Run `npm run build`

**Comment by BeepBeepBopBop** [comment]
My bad, I did not catch those thanks for pointing it out.
